package io.smallrye.context.storage;

import java.util.List;
import java.util.Map;

/**
 * This class is generated by Quarkus depending on the registered StorageUsers
 */
public class QuarkusContextsImpl implements QuarkusContexts {
    // this comes from RESTEasyContextStorageRequirement.name() and its type parameter
    List<Map<Class<?>, Object>> resteasy;

    // this is only required if QuarkusStorageThreadContext pans out
    @Override
    public QuarkusContexts copy() {
        QuarkusContextsImpl ret = new QuarkusContextsImpl();
        ret.resteasy = this.resteasy;
        return ret;
    }
}